// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uktpbcpzzxbbsoixiioq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrdHBiY3B6enhiYnNvaXhpaW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjk0MDksImV4cCI6MjA2NzY0NTQwOX0.AVM18Gdor--6334AqlNOY_7sdg2DfrVPiiS42xFFN_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});