// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxvmvvmnjwtcjgzpaizp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4dm12dm1uand0Y2pnenBhaXpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Njk0MzMsImV4cCI6MjA2NjQ0NTQzM30.YVFXhAKvKWT0CRcl2Li4xiYQGK5zVXVF1N6iEVq3XdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});